language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.1
before_install:
  - sudo add-apt-repository ppa:fcwu-tw/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install vim-gtk -y
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
